// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cache.proto
// Protobuf C++ Version: 6.31.1

#include "cache.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CacheObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expired_at_{::int64_t{0}},
        type_{static_cast< ::CacheType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CacheObject::CacheObject(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CacheObject_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CacheObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CacheObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CacheObjectDefaultTypeInternal() {}
  union {
    CacheObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CacheObjectDefaultTypeInternal _CacheObject_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_cache_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_cache_2eproto = nullptr;
const ::uint32_t
    TableStruct_cache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CacheObject, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CacheObject, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::CacheObject, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::CacheObject, _impl_.expired_at_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CacheObject)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_CacheObject_default_instance_._instance,
};
const char descriptor_table_protodef_cache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013cache.proto\"I\n\013CacheObject\022\030\n\004type\030\001 \001"
    "(\0162\n.CacheType\022\014\n\004data\030\002 \001(\t\022\022\n\nexpired_"
    "at\030\003 \001(\003*$\n\tCacheType\022\n\n\006STRING\020\000\022\013\n\007INT"
    "EGER\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_cache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cache_2eproto = {
    false,
    false,
    134,
    descriptor_table_protodef_cache_2eproto,
    "cache.proto",
    &descriptor_table_cache_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_cache_2eproto::offsets,
    file_level_enum_descriptors_cache_2eproto,
    file_level_service_descriptors_cache_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CacheType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_cache_2eproto);
  return file_level_enum_descriptors_cache_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CacheType_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class CacheObject::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CacheObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CacheObject, _impl_._has_bits_);
};

CacheObject::CacheObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheObject_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CacheObject)
}
PROTOBUF_NDEBUG_INLINE CacheObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::CacheObject& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_(arena, from.data_) {}

CacheObject::CacheObject(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CacheObject& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheObject_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CacheObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, expired_at_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, expired_at_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, expired_at_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:CacheObject)
}
PROTOBUF_NDEBUG_INLINE CacheObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        data_(arena) {}

inline void CacheObject::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, expired_at_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, expired_at_) +
               sizeof(Impl_::type_));
}
CacheObject::~CacheObject() {
  // @@protoc_insertion_point(destructor:CacheObject)
  SharedDtor(*this);
}
inline void CacheObject::SharedDtor(MessageLite& self) {
  CacheObject& this_ = static_cast<CacheObject&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CacheObject::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CacheObject(arena);
}
constexpr auto CacheObject::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CacheObject),
                                            alignof(CacheObject));
}
constexpr auto CacheObject::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CacheObject_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CacheObject::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CacheObject>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CacheObject::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CacheObject>(), &CacheObject::ByteSizeLong,
              &CacheObject::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CacheObject, _impl_._cached_size_),
          false,
      },
      &CacheObject::kDescriptorMethods,
      &descriptor_table_cache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CacheObject_class_data_ =
        CacheObject::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CacheObject::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CacheObject_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CacheObject_class_data_.tc_table);
  return CacheObject_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 24, 2>
CacheObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CacheObject, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CacheObject_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CacheObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .CacheType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CacheObject, _impl_.type_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.type_)}},
    // string data = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.data_)}},
    // int64 expired_at = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CacheObject, _impl_.expired_at_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.expired_at_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .CacheType type = 1;
    {PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.type_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string data = 2;
    {PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 expired_at = 3;
    {PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.expired_at_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\13\0\4\0\0\0\0\0"
    "CacheObject"
    "data"
  }},
};
PROTOBUF_NOINLINE void CacheObject::Clear() {
// @@protoc_insertion_point(message_clear_start:CacheObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.data_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006u) != 0) {
    ::memset(&_impl_.expired_at_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.expired_at_)) + sizeof(_impl_.type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CacheObject::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CacheObject& this_ = static_cast<const CacheObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CacheObject::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CacheObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:CacheObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .CacheType type = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  // string data = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CacheObject.data");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // int64 expired_at = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_expired_at() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_expired_at(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CacheObject)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CacheObject::ByteSizeLong(const MessageLite& base) {
  const CacheObject& this_ = static_cast<const CacheObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CacheObject::ByteSizeLong() const {
  const CacheObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CacheObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string data = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_data());
      }
    }
    // int64 expired_at = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_expired_at() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_expired_at());
      }
    }
    // .CacheType type = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CacheObject::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CacheObject*>(&to_msg);
  auto& from = static_cast<const CacheObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CacheObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_expired_at() != 0) {
        _this->_impl_.expired_at_ = from._impl_.expired_at_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CacheObject::CopyFrom(const CacheObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CacheObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CacheObject::InternalSwap(CacheObject* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.type_)
      + sizeof(CacheObject::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(CacheObject, _impl_.expired_at_)>(
          reinterpret_cast<char*>(&_impl_.expired_at_),
          reinterpret_cast<char*>(&other->_impl_.expired_at_));
}

::google::protobuf::Metadata CacheObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cache_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
